"""empty message

Revision ID: 4534060b12e1
Revises: 60d989fb62db
Create Date: 2022-09-19 21:51:30.528569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4534060b12e1'
down_revision = '60d989fb62db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oa_finance_apply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('request_content', sa.Text(), nullable=True),
    sa.Column('money', sa.DECIMAL(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AUDITING', 'PASS', 'REJECT', name='oafinanceapplystatusenum'), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('responser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requestor_id'], ['oa_user.id'], ),
    sa.ForeignKeyConstraint(['responser_id'], ['oa_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oa_finance_apply')
    # ### end Alembic commands ###
