"""empty message

Revision ID: 60d989fb62db
Revises: 74fbca4a04e9
Create Date: 2022-09-17 14:19:58.682774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d989fb62db'
down_revision = '74fbca4a04e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oa_absent_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oa_absent_apply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('request_content', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AUDITING', 'PASS', 'REJECT', name='oaabsentstatusenum'), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('responser_id', sa.Integer(), nullable=True),
    sa.Column('absent_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['absent_type_id'], ['oa_absent_type.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['oa_user.id'], ),
    sa.ForeignKeyConstraint(['responser_id'], ['oa_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oa_absent_apply')
    op.drop_table('oa_absent_type')
    # ### end Alembic commands ###
