"""empty message

Revision ID: 74fbca4a04e9
Revises: d375e5fd3a48
Create Date: 2022-09-16 16:32:46.613807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fbca4a04e9'
down_revision = 'd375e5fd3a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oa_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oa_cross_department_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['oa_department.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['oa_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('oa_user', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'oa_user', 'oa_department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oa_user', type_='foreignkey')
    op.drop_column('oa_user', 'department_id')
    op.drop_table('oa_cross_department_association')
    op.drop_table('oa_department')
    # ### end Alembic commands ###
